In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)  #type of arr

numpy.ndarray

In [4]:
arr_1d.ndim # create 1d

1

In [5]:
arr_2d =np.array([[1,2,3,4,],[5,6,7,8]])    #create 2d
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr_2d.ndim   #dimention 

2

In [7]:
arr_2d.size

8

In [8]:
arr_1d.size    #size of array


4

In [9]:
arr_1d.shape

(4,)

In [10]:
#(row,coloum)

In [11]:
arr_2d.shape #shape of array

(2, 4)

In [12]:
arr_2d.dtype # data type

dtype('int32')

In [13]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr_1d

array([1, 2, 3, 4])

In [15]:
mat_1s = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])

In [16]:
print(mat_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
type(mat_1s)

numpy.ndarray

In [18]:
ones_mat =np.ones(5)

In [19]:
print(ones_mat)

[1. 1. 1. 1. 1.]


In [20]:
ones_mat.dtype

dtype('float64')

In [21]:
mx_1s= np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
mx_1s =np.ones((4,5),dtype =int)
print(mx_1s)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
ma_0s= np.zeros((2,5),dtype= int)
print(ma_0s)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [70]:
ma_0s =np.zeros((3,4),dtype= bool ,order= 'C')
print(ma_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [62]:
ma_one =np.ones((3,6),dtype = bool)
print(ma_one)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [25]:
ma_str =''
print(bool(ma_str))

False


In [26]:
max_str ='hello'
print(bool(max_str))

True


In [27]:
max_str =np.zeros((3,4),dtype= str)
print(max_str)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [28]:
max_str =np.ones((3,4),dtype= str)
print(max_str)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [29]:
print(str(max_str))

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [30]:
em_mx = np.empty((3,4))
print(em_mx)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
em_mx =np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.44659081e-321]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]


# REVISION ---->  1

In [32]:
import numpy as np

In [33]:
arr1 = np.array([1,2,3,45])
arr1

array([ 1,  2,  3, 45])

In [34]:
type(arr1)

numpy.ndarray

In [35]:
arr1.ndim

1

In [36]:
arr1.size

4

In [37]:
arr1.dtype

dtype('int32')

In [38]:
d2_arr =np.array([[1,2,3,4,],[2,3,4,3]])
d2_arr

array([[1, 2, 3, 4],
       [2, 3, 4, 3]])

In [39]:
type(d2_arr)

numpy.ndarray

In [40]:
d2_arr.ndim

2

In [41]:
mat1 = np.array([[[12,2,2,3],[1,3,4,5],[22,66,3,5]],[[1,2,3,4],[33,44,55,3],[6,7,8,9]]])

In [42]:
mat1

array([[[12,  2,  2,  3],
        [ 1,  3,  4,  5],
        [22, 66,  3,  5]],

       [[ 1,  2,  3,  4],
        [33, 44, 55,  3],
        [ 6,  7,  8,  9]]])

In [43]:
mat1.dtype

dtype('int32')

In [44]:
mat1.ndim

3

In [45]:
mat1.size

24

In [46]:
matrix1 = np.array([[1,2,3,4],[12,3,34,4]])

In [47]:
matrix2 = np.array([[1,2,3,4],[12,3,34,4]])

In [48]:
matrix1 +matrix2

array([[ 2,  4,  6,  8],
       [24,  6, 68,  8]])

In [49]:
matrix1 * matrix2

array([[   1,    4,    9,   16],
       [ 144,    9, 1156,   16]])

In [50]:
mat = np.ones(5)

mat

array([1., 1., 1., 1., 1.])

In [51]:
mat = np.ones((2,6,2))
mat

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
mat.ndim

3

In [53]:
m =np.zeros((2,5))

In [54]:
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
m =np.empty((5,2))

In [56]:
m

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
m.ndim

2

In [58]:
m.ndim

2

In [59]:
se ="helllo"

In [60]:
print(bool(se))

True


# revision 2

In [114]:
arry = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a=arry.ndim
b=type(arry)
c= type(str(arry))
d= arry.shape
e= arry.dtype
ones = np.ones((2,2))
ones1 = np.ones((2,2),dtype = bool)
zeros = np.zeros((2,3),dtype= float)
empty = np.empty((2,3),dtype =bool)
empty1 = np.empty((2,3),dtype =str)
string = "swadesh"," swadesh"
f=  bool(string)
mtx1 =np.array([[[1,1,1],[1,2,3],[2,3,4]],[[1,1,1],[1,2,3],[2,3,4]]])
mtx2 =np.array([[[1,1,1],[1,2,3],[2,3,4]],[[1,1,1],[1,2,3],[2,3,4]]])
g= mtx1.size

print(arry,"\n")
print("dim = " ,a)
print("dtype = " ,b)
print(c)
print(d)
print(e)
print(ones,"\n")
print(ones1)
print(zeros)
print(ma_str)
print(empty)
print(string)
print(f,"\n")
print(empty1)
print(g)
mtx1 +mtx2


[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

dim =  3
dtype =  <class 'numpy.ndarray'>
<class 'str'>
(1, 3, 3)
int32
[[1. 1.]
 [1. 1.]] 

[[ True  True]
 [ True  True]]
[[0. 0. 0.]
 [0. 0. 0.]]
 
[[False False False]
 [False False False]]
('swadesh', ' swadesh')
True 

[['' '' '']
 ['' '' '']]
18


array([[[2, 2, 2],
        [2, 4, 6],
        [4, 6, 8]],

       [[2, 2, 2],
        [2, 4, 6],
        [4, 6, 8]]])