# NUMPY FUNCTION:

In [1]:
import numpy as np

# arange()

In [2]:
#np.arange   (star,end ,steps)
arr_1d =np.arange(1,21)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
even_1darr =np.arange(2,21,2)
print("one diention array == ",even_1darr)

one diention array ==  [ 2  4  6  8 10 12 14 16 18 20]


# linspace

In [4]:
# np.linspace(star ,end, num of values) for array
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [22]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# reshape()

In [25]:
ar_2d =arr_1d.reshape(5,4)
print(ar_2d)                         #it ues forconvert the 1d into 2d arr

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [26]:
ar_2d.ndim

2

In [6]:
a_1d= np.arange(1,21)
print(a_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
#reshape(dim/page ,row, col)
a_3d= a_1d.reshape(1,5,4)
print(a_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]]


In [8]:
a_3d.ndim

3

In [10]:
a_3d =a_1d.reshape(2,2,5)
print(a_3d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [11]:
ar= np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [33]:
# convert 2d arr into 1d arr.
#ar.ravel()
a_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# flatten()

In [13]:
# convert multi arr into 1d arr 
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
a_3d =a_1d.reshape(2,2,5)
a_3d.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# transpose()

In [14]:
# convert row into colum and colum into row
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# REVISION --->2

In [15]:
arr1d = np.arange(1,21).reshape(2,5,2)

In [16]:
arr1d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
arr1d.ndim

3

In [18]:
arr1d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [19]:
arr1d.transpose()


array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [36]:
arr1d.ndim

3

In [20]:
arr1d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
arr1d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# arange(start ,end-1 ,step)  ,
linspace(start ,end,num of value )
# reval() = flatten()  ,
reshape(page, row, col),
# transpose()