# RANDOM Sampling with numpy

In [1]:
import numpy as np
import random as rdm

In [2]:
np.random.random(1) #random me 1 shape h (row)

array([0.87459176])

In [3]:
np.random.random((1,3)) # for create arr , random((row, colom))

array([[0.35398417, 0.79261145, 0.14132137]])

In [4]:
np.random.random((4,3))

array([[0.40522459, 0.46770176, 0.61511403],
       [0.7436018 , 0.43814374, 0.06738242],
       [0.64583106, 0.95616746, 0.84791168],
       [0.31256802, 0.52441615, 0.45315345]])

In [6]:
np.random.randint(1,4)315345]])
1,4
       [0.7436018 , 0.43814374, 0.06738242],
       [0.64583106, 0.95616746, 0.84791168],
       [0.31256802, 0.52441615, 0.45315345]])
315345]])
1,4
np.random.randint(1,4)
2
np.random.randint(1,4,(2,4,4))   #2d array
np.random.randint(1,4,(2,4,4))   #2d array
array([[[2, 3, 3, 3],
        [3, 3, 2, 1],
np.random.randint(1,4)315345]])
np.random.randint(1,4)
2
np.random.randint(1,4,(2,4,4))   #2d array
np.random.randint(1,4,(2,4,4))   #2d array
array([[[2, 3, 3, 3],
        [3, 3, 2, 1],

2

In [8]:
np.random.randint(1,4,(2,4,4))   #2d array

array([[[2, 3, 3, 3],
        [3, 3, 2, 1],
        [3, 1, 3, 1],
        [2, 3, 3, 2]],

       [[2, 3, 2, 2],
        [1, 2, 3, 2],
        [3, 1, 2, 2],
        [2, 2, 2, 1]]])

In [9]:
np.random.randint(1,4,(1,4,4))#1d array

array([[[3, 2, 2, 1],
        [3, 2, 1, 1],
        [1, 1, 3, 2],
        [2, 1, 3, 2]]])

In [10]:
np.random.randint(1,4,(3,4,4)) #3d array

array([[[1, 1, 2, 1],
        [1, 2, 3, 1],
        [1, 2, 2, 3],
        [2, 1, 1, 2]],

       [[2, 2, 2, 2],
        [1, 1, 2, 3],
        [3, 3, 2, 2],
        [3, 2, 3, 1]],

       [[3, 3, 2, 1],
        [2, 2, 2, 3],
        [3, 1, 1, 3],
        [3, 1, 1, 2]]])

In [14]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [15]:
2**32 -1

4294967295

In [16]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [17]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [18]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [19]:
x =[1,2,3,4,5,6]
np.random.choice(x)

1

In [20]:
for i in range(1,11):
    print(np.random.choice(x))

1
5
6
5
1
1
3
5
3
1


In [21]:
x

[1, 2, 3, 4, 5, 6]

In [22]:
np.random.permutation(x)

array([3, 5, 2, 4, 1, 6])

In [23]:
np.random.permutation(x)

array([2, 4, 1, 5, 3, 6])

In [24]:
np.random.permutation(x)

array([6, 2, 4, 3, 1, 5])