# matheatical operation using nupy

In [1]:
import numpy as np

In [2]:
arr1 =np.arange(1,10).reshape(3,3)
arr2 =np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
arr1 -arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [6]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
arr1 @ arr2  #production of 2 matrix

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [11]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
arr2.dot(arr1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [13]:
arr1



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr1.max()

9

In [15]:
arr1.argmax() #maximum value ka index

8

In [16]:
arr1.max(axis=0) # 0 for row

array([7, 8, 9])

In [17]:
arr1.max(axis =1) # 1 for colom

array([3, 6, 9])

In [18]:
arr1.min()

1

In [19]:
arr1.argmin() # for index of min value

0

In [20]:
arr1.min(axis =0)

array([1, 2, 3])

In [21]:
arr1.min(axis =1)

array([1, 4, 7])

In [22]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.sum(arr1)

45

In [25]:
np.sum(arr1,axis =0) # sum ofeach rows

array([12, 15, 18])

In [26]:
np.sum(arr2,axis=1)#sum for each coloum

array([ 6, 15, 24])

In [27]:
 np.mean(arr1) # average of arr
    

5.0

In [28]:
np.mean(arr1,axis =0)

array([4., 5., 6.])

In [29]:
np.sqrt(arr1) #sqrt of each element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
np.std(arr1)#standerd division 

2.581988897471611

In [31]:
np.exp(arr1) #exponent

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [32]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [33]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# Rivision --> 1(part --->1 ,2)

In [ ]:
# arr_3d = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,8],[1,4,5,6,8]]])
arr_3 = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,8],[1,4,5,6,8]]])

a=arr_3d.shape
aa=arr_3d.size
az=arr_3d.ndim
q=arr_3d.dtype
w=type(arr_3d)
ones= np.ones((1,2),dtype= bool)
epty=np.empty((1,2),dtype=int)
zero=np.zeros((2,7),dtype=str)
print(a,"---",aa,"---",az,"----",q,"----",w)
#arr_3d *arr_3

w=np.arange(1,21).reshape(4,1,5)
q=np.linspace(1,5,8)
d=np.ravel(w)
dd=w.flatten()
b=w.transpose()
#print(d,"\n",dd,"\n",b,"\n",w)
print(ones)
print(epty)
print(zero)

# Rivision ---->1

In [106]:
mat1 =np.arange(1,21).reshape(4,5)
mat2 =np.arange(1,21).reshape(4,5)
arr1 =np.arange(1,20)
arr2 =np.arange(1,20)

prdcn = arr1 @ arr2
f =arr1.dot(arr2)
ff= np.add(arr1,arr2)
ffs= np.subtract(arr1 ,arr2)
df = np.divide(arr1 ,arr2)
print(prdcn,"\n",f,"\n",ff,"\n",ffs,"\n",df,"\n")


a=mat1.min()
aa=mat1.max()
aaa= mat1.min(axis=1) #for col
ass = mat1.max(axis=0) #forrow
qa= mat1.sum()
e = np.argmax(mat1)  #index of min value

print(a,"\n",aaa,"\n",aa,"\n",ass,"\n",qa,"\n","\n---",e)
x= np.mean(mat1)
c= np.sqrt(mat1)
v =np.log(mat1)
b= np.log10(mat1)
bb =np.exp(mat2)
st= np.std(mat2)
print(x,"\n\n",c,"\n\n",v,"\n\n",b,"\n\n",bb)

2470 
 2470 
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38] 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

1 
 [ 1  6 11 16] 
 20 
 [16 17 18 19 20] 
 210 
 
--- 19
10.5 

 [[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595]] 

 [[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]
 [2.77258872 2.83321334 2.89037176 2.94443898 2.99573227]] 

 [[0.         0.30103    0.47712125 0.60205999 0.69897   ]
 [0.77815125 0.84509804 0.90308999 0.95424251 1.        ]
 [1.04139269 1.07918125 1.11394335 1.14612804 1.17609126]
 [1.20411998 1.23044892 1.25527251 1.2787536  1.30103   ]] 

 [[2.71828183e+00 7.38905610e+00 2.00855369e+01 5